spring:
  datasource:
    url: jdbc:mysql://ip:port/springjooq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: xxxxx
    password: xxxxx
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8080
